# Generated by Django 4.0.5 on 2022-07-10 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_thumbnail_alter_post_content_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
