# Generated by Django 4.0.5 on 2022-07-29 00:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_post_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
